### ISSUE TITLE
Semantics of `Spot`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#14]
Updating market prices for ilks.

### Data

- [x] `SpotIlk` (with `pip` and `mat`)
- [x] `wards`
- [x] `spot-ilks`

### Operations

- [x] `poke` - updates the `vat-ilks` to adjust the `spot` of that given Ilk.

**Comment by gtrepta** [comment]
Implemented, waiting on https://github.com/runtimeverification/mkr-mcd-spec/pull/21 to open a PR.

**Comment by gtrepta** [comment]
#27
