### ISSUE TITLE
Stub out remaining definition

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#17]
Good for (1) architecture of project, and (2) providing benchmark of progress.

First pass: one markdown file per box on this diagram https://github.com/makerdao/developerguides/blob/master/mcd/mcd-101/mcd-101.md#smart-contract-modules

done with https://github.com/runtimeverification/mkr-mcd-spec/pull/21

**Comment by gtrepta** [comment]
Implemented in https://github.com/runtimeverification/mkr-mcd-spec/pull/21 , pending merge.
