### ISSUE TITLE
Investigate exceptions/state-roll back and authorization scheme

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#28]
It would be easier to implement state-rollback globally, but it may be the case that partial roll-backs and error recovery are possible. If so, then we'll need something more careful.

Please report here findings about this, and the plan on how to give this semantics.

**Comment by dwightguth** [comment]
Just discussed with maker folks: they don't expect us to have to worry about any kind of reentry. In general, the only contracts in the system that call other contracts that aren't fully trusted (ie part of the system) are the token adapters, which call token contracts, and these contracts have been audited by humans to ensure they are not malicious. It is possible but unlikely that the auditors would miss something and a malicious token would get included in the system that has some kind of reentrancy that we would be unable to model, but this is not the intent of the system. Given this, it should be safe to assume that all rollbacks are total rollbacks.
