### ISSUE TITLE
Implement functions for stubs in `flapper`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#32]
First post to issue what needs to be done for flapper, and high level description of what it does.

- [x] Flap . kick
Called by Vow. Put up a new DAI lot for auction.
- [x] Flap . tend
Called by a user. Make a bid for the lot. Refunds the previous bidder's bid.
- [x] Flap . deal
Auction settlement. Sends the lot over to the highest bidder, and burns his or her bid.
- [x] Flap . cage
Part of Global Settlement. Freezes any further bidding.
- [x] Flap . yank
More Global Settlement. Looks like a way for a bidder to take back his or her bid when the auction is frozen.

**Comment by gtrepta** [comment]
Flap is a surplus auction, initiated by Vow.

https://github.com/makerdao/dss/wiki/Auctions#flap---surplus-auction

- [ ] Flap . kick
Called by Vow. Put up a new DAI lot for auction.
- [ ] Flap . tend
Called by a user. Make a bid for the lot. Refunds the previous bidder's bid.
- [ ] Flap . deal
Auction settlement. Sends the lot over to the highest bidder, and burns his or her bid.
- [ ] Flap . cage
Part of Global Settlement. Freezes any further bidding.
- [ ] Flap . yank
More Global Settlement. Looks like a way for a bidder to take back his or her bid when the auction is frozen.
