### ISSUE TITLE
Semantics of `Jug`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#5]
### Data

- [x] `JugIlk`

### Configuration

- [x] `<ilks>`
- [x] `<vat>` Do we need a new cell for this or do we just use the already existing vat-* cells?
- [x] `<vow>`
- [x] `<base>`

### Operations

- [x] `Jug . init`
- [x] `Jug . drip`

### Invariants

???

**Comment by gtrepta** [comment]
https://github.com/runtimeverification/mkr-mcd-spec/pull/9
