### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#64]
Original Proposal
-------------------------

### Introduction

Maker has developed the MCD system to allow pooled backing currencies to their Dai
stable-coin. This requires more care than a single backing currency, and Maker has worked hard to ensure
that the developed EVM bytecode for implementing this on Ethereum meets formal correctness
specifications. However, the individual correctness proofs do not provide a high-level model of the entire
system (abstracting away the EVM), which we propose to do here.
This is in response to the call for security audits at:
https://www.notion.so/MCD-Security-Audit-54f149edffea4bd39c8d3f03e4555e40. Note that we are not
proposing a security audit (which perhaps should still be performed independent of this proposal), rather
we are offering a high-level model of the MCD system. The call details four components of the MCD
system, including (i) the core MCD contracts, (ii) the oracle price feeds from a SSB (Secure Scuttlebutt)
network, (iii) the frontend contracts which users can interact with, and (iv) the permissions system which
allows maintainers to update the contracts and state.

### Deliverables

In all cases, the deliverable is a K specification. We will model all 4 components above to varying
degrees of abstraction (depending on the component in question). In all cases, the specification will be
independent of the underlying bytecode, which is assumed to be solid. Note this means that failures due to
EVM-specific issues such as (i) integer overflow, (ii) out-of-gas, or (iii) stack over/underflow will not be
exposed in this system. The goal is a high-level model of the financial system MCD, not functional
correctness of the EVM bytecode which implements it.

-   K specification of the high-level logic of the core contracts, showing the internal transitions
which are allowed in the system.
-   K specification of the Oracle price feeds, abstracting away details of SSB.
-   K specification of the frontends, showing the allowed interactions users may have with the MCD
system.
-   K specification of the permissions network, showing how permissions may evolve over time.

### Milestones

Listed below are the five principal milestones for this engagement. The purpose of the first
milestone is to adequately research, plan, and prepare for milestones 2 through 4.

1.  Meet with MCD devs to flesh out a high-level english description of
what behaviors need to be specified and what level of detail they should be abstracted at.
2.  Develop the K specification of the high-level behaviors of the MCD core
contracts. This will describe entry/exit points of the contracts, and overall state-updates that each
operation in the system should have.
3.  K specification of the frontend interactions. Similarly this will describe
the high-level transitions that a user should be allowed to induce.
4.  K specification of the permissions logic. This will describe the allowed
transfers of ownership and executive control of the MCD contracts.
5.  K specification of the Oracle price feed. No focus will be put on
modelling SSB, it will be assumed that the price is faithfully and correctly relayed to the
Ethereum contracts.

Extensions
---------------

We proposed 3 rough extensions of this project as a way to get MKR folks excited about the project (in meeting: https://github.com/runtimeverification/mkr-mcd-spec/issues/22#issuecomment-532426836):

(i) generating documentation,
(ii) statistical model checking, and
(iii) fuzzing/test generation for the Solidity code.

The rough consensus was that (ii) -> (iii) -> (i) is the order of priority.

Draft a paragraph or two about these options so that the MKR folks can discuss them, and any other options that might make sense.

**Comment by ehildenb** [comment]
### Test Generation for Solidity Code

Currently the Solidity code is tested using Solidity tests. As new code is written, new tests must be added. We can write a tool which:

-    Fuzzes tests over the KMCD definition, then
-    Translates said tests into Solidity/Truffle tests over the Solidity code.

**Comment by ehildenb** [comment]
It seems that the common theme here is that we need:

-   Conformance testing of the semantics, and
-   A fuzzer over the semantics.

Then both (ii) and (iii) and easier to do.

**Comment by iamchrissmith** [comment]
This week - event emission = Victory on Milestone 2
Then Start Milestone 3:
Next week and the week after they will work on conformance testing (baseline for other steps and to generate confidence in the model).
- using data we gave them about transactions

Then start working on the fuzzing (generating random data)

Then building up the probability distributions

**Comment by ehildenb** [comment]
Next Milestones (to replace milestones 3-5 in the above proposal):

3.  (4 weeks) Conformance testing of the semantics.
    a.  (1 week) - Convert the existing extracted output from `mcd-pyk.py` from `sneak-tx.json` into the correct format for inserting into the configuration and invoking `krun` with. This means using the pre-states from the state diffs and the list of function calls to populate the configuration.
    b.  (1 week) - Check the output of `krun` against the the post-state of the state-diffs, with sensible output when there are differences.
    c.  (2 weeks) - Fix bugs discovered in 3.a and 3.b.

4.  Fuzzing of the semantics to gain higher confidence of conformance with the Solidity.
    a.  (2 weeks) - Develop profile of "likely" calls (eg., normal users will call un-`auth`ed functions, and admins will call `auth`-ed functions). Also come up with "normal" sequences of actions that each class of users will make.
    b.  (1 week) - Define what a "bad" state of the KMCD system would be, in terms of the entire system being too risky, or some individual components of the system being too risky.
    c.  (2 weeks) - Generate and feed random sequences into the KMCD model, checking if the resulting execution traces ever enter a "bad" state defined in 2.b.
    d.  (optional 2 weeks) - Produce adapter which feeds the fuzzed input sequences into the the EVM implementation of MCD, for further conformance testing of the KMCD and Soldiity-MCD.

**Comment by ehildenb** [comment]
re. statistical model checking, after discussing with @malturki we aren't sure if this system actually warrants doing full-blown statistical verification or if that would be overkill. Either way, developing a fuzzing interface is a necessary first step, and the statistical part can be done as an extension later.

Because there aren't obvious probabilistic inputs to the system, modelling it purely nondeterministically (with a fuzzer) may make more sense anyway.

**Comment by ehildenb** [comment]
Accelerated timeline for MCD launch
---------------------------------------------------

Ideally if there are issues with the system, we will be finding them by week 4 at the latest.

### Week 1

-   Discover system variables and macro-measurables which we want to state properties over (on paper). Translate these properties into checks over execution traces (on paper).
-   Setup testing harness over EVM bytecode and KMCD model (using existing data provided by MKR).

### Week 2

-   Translate on paper execution trace properties into python code which checks the actual execution traces of the system.
-   Setup random testing by generating sequences of data in same format that MKR supplied tests are supplied.

### Week 3

-   Break model in ways found by bug bounty program. See if state properties and random testing heuristics actually catches these breakages in the system.
-   Begin running the random tester continuously on the current system.

### Week 4

-   Investigate whether we can quantify how much of state-space the random tester has covered (may not be entirely feasible).
-   Additional tuning and reporting of results.

### Week 5

-   Additional tuning and reporting of work.

**Comment by ehildenb** [comment]
Obsolete, moved to Google docs.
